import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "swiper/css";
import Providers from "./store/Providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Order",
  description: "Generated by create next app",
};


function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang='en'>
      <Providers>
        <body className={inter.className}>
          {children}
        </body>
      </Providers>
    </html>
  );
}

export default RootLayout;
